import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import StoreProvider from 'providers/StoreProvider'
import Header from '@/components/layout/header/Header'
import { Toaster } from 'sonner'
import SubHeader from '@/components/layout/header/SubHeader'
import { UserRole } from '@/types/userRole'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'STEMify Education',
  description: 'Generated by create next app'
}

const role: UserRole = UserRole.STUDENT

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} bg-bg-light antialiased`}>
        <StoreProvider>
          {/* Header */}
          <header className='sticky top-0 z-50 shadow-sm backdrop-blur-md'>
            <div className='mx-auto max-w-6xl px-4 py-4 sm:px-6 lg:px-8'>
              <Header />
            </div>
          </header>

          {/* Main Content */}
          <main className='mx-auto max-w-6xl px-4 py-4 sm:px-6 lg:px-8'>{children}</main>

          {/* Footer */}
          <footer></footer>
        </StoreProvider>
        <Toaster />
      </body>
    </html>
  )
}
