import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'
import StoreProvider from 'providers/StoreProvider'
import { Toaster } from 'sonner'
import { ModalProvider } from '@/providers/ModalProvider'
import { SessionProvider } from 'next-auth/react'
import AuthSessionSync from '@/providers/AuthSessionSync'
import Providers from '@/providers/Providers'

const geistNunito = Nunito({
  variable: '--font-geist-nunito',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'STEMify Education',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico'
  }
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className={`${geistNunito.variable}`}>
      <body className={`antialiased`}>
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
