import Providers from '@/providers/Providers'
import SignalRProvider from '@/providers/SignalRProvider'
import { loadMessages } from 'i18n/loadMessages'
import { routing } from 'i18n/routing'
import { Metadata } from 'next'
import { hasLocale, NextIntlClientProvider } from 'next-intl'
import { notFound } from 'next/navigation'
import { Nunito, Reem_Kufi } from 'next/font/google'
import './globals.css'

const geistNunito = Nunito({
  variable: '--font-geist-nunito',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap'
})

const fontReemKufi = Reem_Kufi({
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'STEMify Education',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico'
  }
}

export default async function RootLayout({
  children,
  params
}: Readonly<{ children: React.ReactNode; params: { locale: string } }>) {
  const { locale } = await params

  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }

  let messages
  try {
    messages = await loadMessages(locale)
  } catch (error) {
    notFound()
  }

  return (
    <html lang={locale} className={fontReemKufi.className}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Providers>
            <main>
              {/* <SignalRProvider>{children}</SignalRProvider> */}
              {children}
            </main>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
